Runtime is Copyright (C) 2010-2013, Benjamin Negrevergne.

* Runtime

Run experiments and plot the results in a reproducible way.  

** Description 

Runtime can be used to measure and plot statistics such as time or
memory usage on programs with a (possibly large) number of parameters.

For example the following command:

 $> runtime -p P1 a1 a2 -p P2 b1 b2 b3 -u P1cxP2l -- echo P1 P2

will 
1. Run the following commands 

echo a1 b1
echo a1 b2
echo a1 b3
echo a2 b1
echo a2 b2
echo a2 b3

2. Collect time and memory statistics and store them into file. 
One value per column for P1, one value per line for P2.

3. Store the results in files, lines and columns according to format
specifications in the using expression.  In our example P1cxP2l means
that time (and memory) results will be stored one value per column for
P1 and one value per line for P2.

This will lead to the following layout in the output file. 

# P2    P1=a1   P1=a2
b1      0.00    0.00
b2      0.00    0.00
b3      0.00    0.00

(time are 0.00 because executing "echo" is almost instantaneous. )

Given this file, plotting is easy (using gnuplot for example.) 

** Dependencies

Runtime requires the following CPAN modules to be available in your @INC path. 

    Proc::ProcessTable
    Parse::RecDescent
    Digest::MD5

See following section for more info about how to install.     

** Install

   Once you have the dependencies installed, you can install Runtime
   using the standard install process, i.e.:

   perl Makefile.PL
   make
   make install 

   For more details about installing Runtime and its dependencies, see INSTALL file. 

** Bug report, questions, comments

Write me at bnegreve@gmail.com
   
** Licence Information

This program is free software; you can redistribute it and/or modify
it under the terms of  Gnu General Public License. For details, see the
full text of the license in the file LICENSE.

This program is distributed in the hope that it will be
useful, but it is provided “as is” and without any express
or implied warranties. For details, see the full text of
the license in the file LICENSE.

Copyright (C) 2010-2013 by Benjamin Negrevergne
