Runtime is Copyright (C) 2010-2013, Benjamin Negrevergne.

* Runtime

** DEPENDENCIES

Runtime requires the following CPAN modules to be available in your @INC path. 

    Proc::ProcessTable
    Parse::RecDescent
    Digest::MD5

See following section for more info about how to install.     

** USER LOCAL INSTALLATION

Before you can run and install Runtime, you need to install a cuple of
CPAN modules. This can be done without system wide permissions
following the following steps. For a system wise installation, see next section.

1. Install a writable perl directory for cpan modules

    cpan (default aswers) 

2. Source your shell config file, for example: 
  
    source ~/.bashrc

3. Download and install the dependencies
    
    cpan Parse::RecDescent Proc::ProcessTable Digest::MD5
    
You can now build and install Runtime.

4. Move to Runtime source tree.
   
   cd /path/to/runtime/sourcetree

5. Build and install    

   perl Makefile.PL
   make
   make test
   make install 

More info about how to install CPAN modules here: 
   www.cpan.org/modules/INSTALL.html

** SYSTEM WISE INSTALLATION 

1. Install the dependencies using the system package manager.
For example, on Debian (and proably Ubuntu) you can install the dependencies as follows:

    sudo apt-get install libproc-processtable-perl libparse-recdescent-perl libdigest-md5-file-perl

(Note that on a different distribution, package names may differs.)

2. Move to Runtime source tree.
   
   cd /path/to/runtime/sourcetree

3. Build and install    

   perl Makefile.PL
   make
   make test
   make install 

3'. If you feel like, you can spefy a different prefix path:

   perl Makefile.PL PREFIX=prefix/
   make
   make test
   make install 

** LICENCE INFORMATION

This program is free software; you can redistribute it and/or modify
it under the terms of  Gnu General Public License. For details, see the
full text of the license in the file LICENSE.

This program is distributed in the hope that it will be
useful, but it is provided “as is” and without any express
or implied warranties. For details, see the full text of
the license in the file LICENSE.

Copyright (C) 2010-2013 by Benjamin Negrevergne
